package com.sc.common;

public interface Code {
	String SUCCESS = "SUCCESS";
	String ERROR_USERNAME_NOTEXIST = "ERROR_USERNAME_NOTEXIST";
	String ERROR_PASSWORD_WRONG = "ERROR_PASSWORD_WRONG";
	
	String ERROR_STUNO_EXIST = "ERROR_STUNO_EXIST";
	String ERROR_CNO_EXIST = "ERROR_CNO_EXIST";
}
